export default {
  LOADING: require('../assets/lottieItems/97952-loading-animation-blue.json'),
  LOADING2: require('../assets/room/button/icons.png'),
  CARD_BACK: require('../assets/images/card/bicycle_blue_1x.png'),
  BACKGROUND: require('../assets/images/Display.png'),
  ICON_3POINTS: require('../assets/icons/3points.png'),
  ICON_SHARE: require('../assets/icons/share.png'),
  ICON_SOUND: require('../assets/icons/sound.png'),
  CHAT: require('../assets/icons/icon_chat.png'),
  ICON_SMILE: require('../assets/icons/icon=smile.png'),
  LOGO: require('../assets/images/logo 1.png'),
  KEY: require('../assets/images/icons (1).png'),
  PERSON: require('../assets/images/icons (2).png'),
  PHONE: require('../assets/images/icons (3).png'),
  EMAIL: require('../assets/images/icons.png'),
  X: require('../assets/images/mage_x.png'),
  GOOGLE: require('../assets/images/Vector (1).png'),
  FACEBOOK: require('../assets/images/Vector.png'),
  SAJADA: require('../assets/room/backgrounds/default.png'),
  STORE: require('../assets/home/Footer/store.png'),
  LEAGUE: require('../assets/home/Footer/league.png'),
  COMMU: require('../assets/home/Footer/commu.png'),
  HOME: require('../assets/home/Footer/main.png'),
  ALERT: require('../assets/home/body/alert.png'),
  HEART: require('../assets/home/body/heart.png'),
  HONOR: require('../assets/home/body/honor.png'),
  STAR: require('../assets/home/body/star.png'),
  YELLOW_STAR: require('../assets/home/body/yellow_star.png'),
  EAGLE: require('../assets/home/body/eagle.png'),
  MARK: require('../assets/home/body/!.png'),
  YELLOW_HEART: require('../assets/roomList/yellow_heart.png'),
  WIN: require('../assets/roomList/win.png'),
  LOSE: require('../assets/roomList/lose.png'),
  CROWN: require('../assets/Store/crown-removebg-preview.png'),
  PLASTIC_CARDS: require('../assets/Store/stacked plastic cards.png'),
  CARD_WITH_CROWN: require('../assets/Store/tarot card with crown.png'),
  WINNER_CUP: require('../assets/Store/winner cup.png'),
  INFINITY: require('../assets/Store/infinity.png'),
  GALLERY: require('../assets/Store/Gallery.png'),
  CARDS_WITH_HEART: require('../assets/Store/cards_with_heart.png'),
  DIAMOND_1: require('../assets/images/one.png'),
  DIAMOND_2: require('../assets/images/two.png'),
  DIAMOND_3: require('../assets/images/three.png'),
  DIAMOND_4: require('../assets/images/four.png'),
  SUBS: require('../assets/Store/subs.png'),
};
